### PR TITLE
Introducing database link support

### LINKED ISSUE #89: Introducing database link support
This solves the issues #54. The new grammar definition is parse tree compatible with the existing grammar.

---
Oracle 12c grammar (simplified):
===

[Oracle Database SQL Language Reference](https://docs.oracle.com/database/121/SQLRF/sql_elements009.htm#SQLRF51132)

database_object_or_part::=

image

dblink::=
image

---
Current sqlparse grammar:
===
```
table -> NAME                                                                                   : unwrap_bin('$1').
table -> NAME NAME                                                                              : {as, unwrap_bin('$1'), unwrap_bin('$2')}.
table -> STRING                                                                                 : unwrap_bin('$1').
table -> NAME '.' NAME                                                                          : list_to_binary([unwrap('$1'),".",unwrap('$3')]).
table -> NAME '.' NAME NAME                                                                     : {as, list_to_binary([unwrap('$1'),".",unwrap('$3')]), unwrap_bin('$4')}.
table -> parameter                                                                              : '$1'.
table -> parameter NAME                                                                         : {as, '$1', unwrap_bin('$2')}.

```

---
New sqlparse grammar:
===
lexer:
```
% database link
[@][A-Za-z0-9_\$#]+                                 : {token, {'DBLINK', TokenLine, TokenChars}.
```

parser:
```
table -> NAME                                                                                   : unwrap_bin('$1').
table -> NAME DBLINK                                                                            : unwrap_bin('$1' ++ '$2').
table -> NAME NAME                                                                              : {as, unwrap_bin('$1'), unwrap_bin('$2')}.
table -> NAME NAME DBLINK                                                                       : {as, unwrap_bin('$1'), unwrap_bin('$2' ++ '$3')}.
table -> STRING                                                                                 : unwrap_bin('$1').
table -> NAME '.' NAME                                                                          : list_to_binary([unwrap('$1'),".",unwrap('$3')]).
table -> NAME '.' NAME DBLINK                                                                   : list_to_binary([unwrap('$1'),".",unwrap('$3' ++ '$4')]).
table -> NAME '.' NAME NAME                                                                     : {as, list_to_binary([unwrap('$1'),".",unwrap('$3')]), unwrap_bin('$4')}.
table -> NAME '.' NAME NAME DBLINK                                                              : {as, list_to_binary([unwrap('$1'),".",unwrap('$3')]), unwrap_bin('$4' ++ '$5')}.
table -> parameter                                                                              : '$1'.
table -> parameter NAME                                                                         : {as, '$1', unwrap_bin('$2')}.
table -> parameter NAME DBLINK                                                                  : {as, '$1', unwrap_bin('$2' ++ '$3')}.
```

### PR DESCRIPTION
**Pull request by walter-weinmann**
fixes #89 

The change reflects the Oracle SQL syntax (Version 12c.2). 

The PR also includes a cleanup action for the permitted use of schema, database link and alias in the table name for the individual SQL statements.

The PR has been tested successfully with the current versions of [dderl](https://github.com/K2InformaticsGmbH/dderl) and [imem](https://github.com/K2InformaticsGmbH/imem/tree/ct_tests).

### CODE REVIEW

**Comment by walter-weinmann** [comment]
Looks fine for me - the first one had a time-out problem :

image

**Comment by c-bik** [comment]
Strange, cuz I am still seeing
image

**Comment by walter-weinmann** [comment]
There are two Travis runs initiated - first one by the push command - second one for the PR - the first one gets in one of the OTP versions a time-out and therefore fails - the second one is fine. There is no problem resulting from the program code.

**Comment by walter-weinmann** [comment]
I've restarted the failing build.

**Pull request merged**
